spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/inpad_scp
          jwk-set-uri: ${spring.security.resourceserver.oauth2.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
auth:
  converter:
    resource-id: inpad_scp
    principle-attribute: preferred_username

#server:
#  port: 8443
#  ssl:
#    key-store-type: PKCS12
#    key-store: keystore.p12
#    key-store-password: changeit
#    key-alias: inpad

